"""Create a baseline migrations

Revision ID: 8e9433d9f273
Revises: 
Create Date: 2024-11-29 19:48:06.171014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e9433d9f273'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dmp_issue_updates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('dmp_issue_updates', 'body_text',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('dmp_issue_updates', 'comment_link',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('dmp_issue_updates', 'comment_api',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('dmp_issue_updates', 'comment_updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('dmp_issue_updates', 'dmp_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'::bigint"))
    op.alter_column('dmp_issue_updates', 'created_by',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'NA'::text"))
    op.drop_constraint('dmp_issue_updates_comment_id_key', 'dmp_issue_updates', type_='unique')
    op.drop_constraint('dmp_issue_updates_dmp_id_fkey', 'dmp_issue_updates', type_='foreignkey')
    op.create_foreign_key(None, 'dmp_issue_updates', 'dmp_orgs', ['dmp_id'], ['id'])
    op.drop_table_comment(
        'dmp_issue_updates',
        existing_comment='Having records of dmp with issue details',
        schema=None
    )
    op.alter_column('dmp_issues', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('dmp_issues', 'issue_number',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'::bigint"))
    op.alter_column('dmp_issues', 'mentor_username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('dmp_issues', 'contributor_username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('dmp_issues', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'NA'::text"))
    op.alter_column('dmp_issues', 'org_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'::bigint"))
    op.alter_column('dmp_issues', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'NA'::text"))
    op.alter_column('dmp_issues', 'repo',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True,
               existing_server_default=sa.text("'NA'::text"))
    op.drop_constraint('dmp_issues_dmp_id_key', 'dmp_issues', type_='unique')
    op.drop_constraint('dmp_issues_org_id_fkey', 'dmp_issues', type_='foreignkey')
    op.create_foreign_key(None, 'dmp_issues', 'dmp_orgs', ['org_id'], ['id'])
    op.drop_column('dmp_issues', 'repo_owner')
    op.alter_column('dmp_orgs', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('dmp_orgs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('dmp_orgs', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('dmp_orgs', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('dmp_orgs', 'link',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('dmp_orgs', 'repo_owner',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'NA'::text"))
    op.drop_constraint('dmp_orgs_id_key', 'dmp_orgs', type_='unique')
    op.alter_column('dmp_pr_updates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('dmp_pr_updates', 'pr_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('dmp_pr_updates', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('dmp_pr_updates', 'pr_updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('dmp_pr_updates', 'merged_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('dmp_pr_updates', 'closed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('dmp_pr_updates', 'dmp_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'::bigint"))
    op.alter_column('dmp_pr_updates', 'link',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'NA'::text"))
    op.drop_constraint('dmp_pr_updates_pr_id_key', 'dmp_pr_updates', type_='unique')
    op.drop_constraint('dmp_pr_updates_dmp_id_fkey', 'dmp_pr_updates', type_='foreignkey')
    op.create_foreign_key(None, 'dmp_pr_updates', 'dmp_issues', ['dmp_id'], ['id'])
    op.drop_table_comment(
        'dmp_pr_updates',
        existing_comment='Having PR related records',
        schema=None
    )
    op.alter_column('dmp_week_updates', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('dmp_week_updates', 'issue_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('dmp_week_updates', 'week',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('dmp_week_updates', 'total_task',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('dmp_week_updates', 'completed_task',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('dmp_week_updates', 'progress',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('dmp_week_updates', 'task_data',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('dmp_week_updates', 'dmp_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.drop_constraint('dmp_week_updates_dmp_id_fkey', 'dmp_week_updates', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('dmp_week_updates_dmp_id_fkey', 'dmp_week_updates', 'dmp_issues', ['dmp_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('dmp_week_updates', 'dmp_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('dmp_week_updates', 'task_data',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('dmp_week_updates', 'progress',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('dmp_week_updates', 'completed_task',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('dmp_week_updates', 'total_task',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('dmp_week_updates', 'week',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('dmp_week_updates', 'issue_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('dmp_week_updates', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'dmp_pr_updates',
        'Having PR related records',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'dmp_pr_updates', type_='foreignkey')
    op.create_foreign_key('dmp_pr_updates_dmp_id_fkey', 'dmp_pr_updates', 'dmp_issues', ['dmp_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_unique_constraint('dmp_pr_updates_pr_id_key', 'dmp_pr_updates', ['pr_id'])
    op.alter_column('dmp_pr_updates', 'link',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'NA'::text"))
    op.alter_column('dmp_pr_updates', 'dmp_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'::bigint"))
    op.alter_column('dmp_pr_updates', 'closed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('dmp_pr_updates', 'merged_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('dmp_pr_updates', 'pr_updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('dmp_pr_updates', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('dmp_pr_updates', 'pr_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('dmp_pr_updates', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('dmp_orgs_id_key', 'dmp_orgs', ['id'])
    op.alter_column('dmp_orgs', 'repo_owner',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'NA'::text"))
    op.alter_column('dmp_orgs', 'link',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('dmp_orgs', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('dmp_orgs', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('dmp_orgs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('dmp_orgs', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('dmp_issues', sa.Column('repo_owner', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dmp_issues', type_='foreignkey')
    op.create_foreign_key('dmp_issues_org_id_fkey', 'dmp_issues', 'dmp_orgs', ['org_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_unique_constraint('dmp_issues_dmp_id_key', 'dmp_issues', ['id'])
    op.alter_column('dmp_issues', 'repo',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'NA'::text"))
    op.alter_column('dmp_issues', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'NA'::text"))
    op.alter_column('dmp_issues', 'org_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'::bigint"))
    op.alter_column('dmp_issues', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'NA'::text"))
    op.alter_column('dmp_issues', 'contributor_username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('dmp_issues', 'mentor_username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('dmp_issues', 'issue_number',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'::bigint"))
    op.alter_column('dmp_issues', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'dmp_issue_updates',
        'Having records of dmp with issue details',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'dmp_issue_updates', type_='foreignkey')
    op.create_foreign_key('dmp_issue_updates_dmp_id_fkey', 'dmp_issue_updates', 'dmp_issues', ['dmp_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_unique_constraint('dmp_issue_updates_comment_id_key', 'dmp_issue_updates', ['comment_id'])
    op.alter_column('dmp_issue_updates', 'created_by',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'NA'::text"))
    op.alter_column('dmp_issue_updates', 'dmp_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'::bigint"))
    op.alter_column('dmp_issue_updates', 'comment_updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('dmp_issue_updates', 'comment_api',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('dmp_issue_updates', 'comment_link',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('dmp_issue_updates', 'body_text',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('dmp_issue_updates', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        # ### end Alembic commands ###
